Repository chodocs/chodocs, pull requests merged in 2023-04, with the labels that each got.

#221 feat(weekly): update 03 and add 04
  docs/.vitepress/sidebar.ts
  docs/weekly/202303.md
  docs/weekly/202304.md
Labels: 📖 documentation

#222 feat(weekly): update 03 and add 04
  docs/weekly/202303.md
Labels: 📖 documentation

#223 feat(nextjs): add post about sitemap generator for next.js
  docs/.vitepress/sidebar.ts
  docs/nextjs/sitemap/index.md
Labels: 📖 documentation

#224 feat(theme): generate feeds for website
  README.md
  docs/.vitepress/config.ts
  docs/.vitepress/link.ts
  docs/.vitepress/plugins/genFeed.ts
  docs/guide.md
  package.json
  pnpm-lock.yaml
Labels: 🚀 features

#225 feat(weekly): update 04
  docs/weekly/202303.md
  docs/weekly/202304.md
Labels: 📖 documentation

#227 feat: add vue3-management-system md
  docs/.vitepress/sidebar.ts
  docs/vuejs/vue3-management-system/index.md
  pnpm-lock.yaml
Labels: 📖 documentation

#228 fix: use pnpm@8 install
  pnpm-lock.yaml
Labels: 🐛 bug need fix

#230 ci: use latest eslint-config to lint fix
  docs/.vitepress/plugins/genFeed.ts
  docs/.vitepress/theme/components/Contributors.vue
  docs/.vitepress/theme/components/CopyRight.vue
  docs/.vitepress/theme/components/NavCard.vue
  docs/.vitepress/theme/components/PageInfo.vue
  docs/.vitepress/theme/plugins/autoSidebarBeta.ts
  docs/.vitepress/theme/plugins/googleAnalytics.ts
  docs/.vitepress/theme/utils/date.ts
  docs/.vitepress/theme/utils/pageInfo.ts
  docs/contributors.ts
  docs/interview/react-summary/index.md
  docs/nextjs/sitemap/index.md
  docs/patterns/provider-pattern/index.md
  docs/patterns/proxy-pattern/demo1.vue
  docs/patterns/proxy-pattern/demo2.vue
  docs/patterns/proxy-pattern/demo3.vue
  docs/patterns/singleton-pattern/demo2.vue
  docs/tool/off-time/demo.vue
Labels: 🔨 optimize code

#233 feat(theme): add umami analytics
  docs/.vitepress/config.ts
  package.json
Labels: 🚀 features

#234 feat(theme): add feed
  docs/.vitepress/plugins/genFeed.ts
Labels: 🔨 optimize code

#235 fix: add guid and update desc
  docs/.vitepress/plugins/genFeed.ts
Labels: 🔨 optimize code

#236 feat(rss): optimize rss object of date
  docs/.vitepress/plugins/genFeed.ts
Labels: 🔨 optimize code

#237 fix(rss): fix title and author
  docs/.vitepress/plugins/genFeed.ts
Labels: 🔨 optimize code

#239 feat(docs): update info and add program
  docs/.vitepress/config.ts
  docs/.vitepress/sidebar.ts
  docs/index.md
  docs/program/index.md
  docs/program/npm-package/index.md
  docs/program/vitepress-algolia-plus/index.md
  docs/program/vitepress-algolia-solved/index.md
  docs/program/vitepress-algolia/index.md
  docs/program/vitepress-local-search/index.md
Labels: 📖 documentation

#242 feat(program): add chodocs vitepress config post
  docs/.vitepress/sidebar.ts
  docs/program/vitepress-plugin/index.md
Labels: 📖 documentation

#244 feat: update stack md
  docs/.vitepress/sidebar.ts
  docs/algorithm/stack/1190.md
  docs/algorithm/stack/1249.md
  docs/algorithm/stack/1249.移除无效的括号.md
  docs/algorithm/stack/20.md
  docs/algorithm/stack/20.有效的括号.md
  docs/algorithm/stack/739.md
  docs/algorithm/stack/901.md
  docs/algorithm/stack/907.md
  docs/algorithm/stack/921.md
  docs/algorithm/stack/921.使括号有效的最少添加.md
  docs/algorithm/stack/946.md
Labels: 📖 documentation

#246 feat(weekly): update weekly 04
  docs/.vitepress/sidebar.ts
  docs/index.md
  docs/weekly/202304.md
  docs/weekly/202305.md
Labels: 📖 documentation
