Repository chodocs/chodocs, pull requests merged in 2023-01, with the labels that each got.

#20 docs: update arc gift
  docs/arc.md
  docs/guide.md
Labels: documentation

#21 feat: add page contributors
  .github/workflows/release.yml
  .gitignore
  docs/.vitepress/config.ts
  docs/.vitepress/metadata/index.ts
  docs/.vitepress/metadata/types.ts
  docs/.vitepress/plugins/contributors.ts
  docs/.vitepress/plugins/markdownTransform.ts
  docs/.vitepress/sidebar.ts
  docs/.vitepress/theme/components/Contributors.vue
  docs/.vitepress/theme/index.ts
  docs/patterns/guide/index.md
  docs/patterns/proxyPattern/index.md
  docs/patterns/singletonPattern/index.md
  docs/vite.config.ts
  package.json
  pnpm-lock.yaml
  scripts/contributors.ts
  scripts/updateMetaData.ts
  scripts/utils.ts
  types/docsTypes.ts
  types/index.ts
  types/metaData.ts
  unocss.config.ts
Labels: enhancement

#22 docs: pr
  docs/patterns/guide/index.md
Labels: documentation

#23 chore: release v0.1.1
  package.json
  pnpm-lock.yaml
  scripts/release.ts
Labels: release

#24 chore: update license name && gitignore
  .gitignore
  LICENSE
  docs/.vitepress/.gitignore
  docs/.vitepress/theme/global.d.ts
  shims.d.ts
Labels: optimize code

#25 ci: update name
  .github/workflows/algolia.yml
  .github/workflows/contributors.yml
Labels: optimize code

#27 ci: update
  .github/workflows/contributors.yml
Labels: optimize code

#28 feat: add contributors github link
  docs/.vitepress/theme/components/Contributors.vue
Labels: enhancement

#29 docs: optimize members
  docs/index.md
  docs/public/socialIcons.ts
Labels: optimize code

#30 docs: update readme
  README.md
Labels: documentation

#32 chore: change pkg
  package.json
Labels: optimize code

#36 chore: add npmrc && upgrade vitepress
  .npmrc
  package.json
  pnpm-lock.yaml
Labels: package

#35 docs(interview): add react interview 2023
  docs/.vitepress/config.ts
  docs/.vitepress/sidebar.ts
  docs/essay/hl1.md
  docs/interview/React/react-summary.md
  docs/interview/index.md
Labels: documentation

#39 feat: add changelog
  docs/.vitepress/metadata/types.ts
  docs/.vitepress/plugins/changelog.ts
  docs/.vitepress/plugins/markdownTransform.ts
  docs/.vitepress/sidebar.ts
  docs/.vitepress/theme/components/Changelog.vue
  docs/.vitepress/theme/utils.ts
  docs/algorithm/guide/index.md
  docs/vite.config.ts
  meta/packages.ts
  package.json
  pnpm-lock.yaml
  scripts/changelog.ts
  scripts/updateMetaData.ts
  scripts/utils.ts
Labels: enhancement

#40 feat: add updateContributors on release
  docs/.vitepress/sidebar.ts
  docs/contributors.json
  docs/interview/react-summary/index.md
  docs/vite.config.ts
  package.json
  pnpm-lock.yaml
  scripts/release.ts
  scripts/utils.ts
Labels: enhancement, chore: release

#42 docs: update repo info
  README.md
  docs/.vitepress/config.ts
  docs/.vitepress/link.ts
  docs/program/ch1.md
  package.json
  scripts/utils.ts
Labels: documentation

#44 fix: remove private account
  docs/.vitepress/theme/components/Contributors.vue
  scripts/contributors.ts
Labels: 🐛 bug need fix, 🔨 optimize code

#45 docs(interview): change title
  docs/interview/react-summary/index.md
Labels: 📖 documentation

#46 feat: md support demo container && update patterns docs
  docs/.vitepress/sidebar.ts
  docs/.vitepress/theme/components/DemoContainer.vue
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/styles/demo.css
  docs/.vitepress/theme/styles/vars.css
  docs/patterns/proxy-pattern/index.md
  docs/patterns/singleton-pattern/demo1.vue
  docs/patterns/singleton-pattern/demo2.vue
  docs/patterns/singleton-pattern/index.md
  docs/patterns/singleton-pattern/utils.ts
  docs/postcss.config.js
  package.json
  pnpm-lock.yaml
Labels: 📖 documentation, 🚀 features

#48 chore: release v0.1.4
  package.json
Labels: 🎉 chore: release

#49 docs: update demo link
  docs/patterns/singleton-pattern/index.md
Labels: 📖 documentation

#50 docs: add finalcut pro hot key
  docs/.vitepress/sidebar.ts
  docs/tool/finalcut/index.md
Labels: 📖 documentation

#51 feat: add video link component && update docs
  docs/.vitepress/sidebar.ts
  docs/.vitepress/theme/components/VideoLink.vue
  docs/2022.md
  docs/essay/hl1.md
  docs/memo/git-command/index.md
  docs/patterns/singleton-pattern/index.md
  docs/program/npm-package/index.md
  docs/program/vitepress-algolia/index.md
  meta/packages.ts
  package.json
  pnpm-lock.yaml
Labels: 📖 documentation, 🚀 features

#53 chore: release v0.1.5
  docs/contributors.json
  package.json
Labels: 🎉 chore: release

#54 ci: add add workflow permission
  .github/workflows/release.yml
Labels: 🔨 optimize code

#55 ci: add workflow permissions
  .github/workflows/contributors.yml
Labels: 🔨 optimize code

#56 feat: changelog add docs message
  scripts/changelog.ts
Labels: 🔨 optimize code

#57 feat: remove md symbol new && md update
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/plugins/symbol.ts
  docs/2022.md
  docs/arc.md
  docs/program/vitepress-algolia/index.md
Labels: 📖 documentation, 🔨 optimize code

#60 chore: release v0.1.7
  package.json
Labels: 🎉 chore: release

#61 fix: set to get
  docs/patterns/proxy-pattern/demo2.vue
Labels: 📖 documentation

#64 feat(algorithm): add mind Mapping
  docs/algorithm/guide/index.md
Labels: 📖 documentation

#65 feat: add interviewer qa docs
  docs/.vitepress/sidebar.ts
  docs/interview/spring-internship/bytedance-preparation/index.md
  docs/interview/spring-internship/guide/index.md
  docs/interview/spring-internship/interviewer/index.md
Labels: 📖 documentation

#66 docs: del layout recommend && update content
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/ChoLayout.vue
  docs/.vitepress/theme/index.ts
  docs/arc.md
  docs/guide.md
Labels: 📖 documentation

#67 feat: update ci && import bvId
  .github/workflows/contributors.yml
  docs/interview/index.md
  docs/interview/spring-internship/interviewer/index.md
  docs/patterns/proxy-pattern/index.md
Labels: 📖 documentation

#68 feat: new year plan
  docs/.vitepress/config.ts
  docs/.vitepress/sidebar.ts
  docs/.vitepress/theme/components/ContentBox.vue
  docs/interview/index.md
  docs/plan/card.vue
  docs/plan/index.md
  docs/plan/list1/done.md
  docs/plan/list1/todo.md
  docs/plan/list2/done.md
  docs/plan/list2/todo.md
  docs/public/img/2023plan1.png
Labels: 📖 documentation

#69 docs: add main branch && add provider-pattern
  .github/workflows/contributors.yml
  README.md
  docs/.vitepress/sidebar.ts
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/styles/global.css
  docs/memo/git-command/index.md
  docs/patterns/provider-pattern/index.md
Labels: 📖 documentation
