Repository chodocs/chodocs, pull requests merged in 2023-02, with the labels that each got.

#76 feat: resolve social icons path info
  docs/index.md
  docs/socialIcons.ts
Labels: 🔨 optimize code

#79 fix: eslint error of ts
  .eslintcache
  docs/patterns/provider-pattern/index.md
  docs/socialIcons.ts
  package.json
  pnpm-lock.yaml
Labels: 🐛 bug need fix

#80 feat: git ignore cache of eslint
  .gitignore
Labels: 🔨 optimize code

#78 ci: add ci yml
  .github/workflows/ci.yml
  package.json
Labels: 🔨 optimize code

#71 docs: add prototype pattern
  docs/.vitepress/sidebar.ts
  docs/patterns/prototype-pattern/index.md
  docs/plan/list2/done.md
  docs/plan/list2/todo.md
  docs/public/patterns/prototype/1.png
  docs/public/patterns/prototype/2.png
Labels: 📖 documentation

#81 feat: add tool of cal off time
  docs/.vitepress/sidebar.ts
  docs/tool/off-time/demo.vue
  docs/tool/off-time/index.md
  package.json
  pnpm-lock.yaml
Labels: 📖 documentation, 🚀 features

#82 fix: remove how_long_off var
  docs/tool/off-time/demo.vue
Labels: 🔨 optimize code

#83 docs: update contributors
  README.md
Labels: 📖 documentation

#86 fix: time left conditional
  docs/tool/off-time/demo.vue
Labels: 🔨 optimize code

#90 docs: add websocket.md
  docs/.vitepress/sidebar.ts
  docs/interview/net/websocket/index.md
Labels: 📖 documentation

#72 fix: contributors in all page
  docs/.vitepress/plugins/markdownTransform.ts
  docs/.vitepress/theme/components/Contributors.vue
  docs/interview/react-summary/index.md
  docs/tool/off-time/demo.vue
  meta/packages.ts
  scripts/contributors.ts
  scripts/updateMetaData.ts
  types/metaData.ts
Labels: 🐛 bug need fix, 🔨 optimize code

#91 feat: add system interview
  docs/.vitepress/sidebar.ts
  docs/interview/net/http/index.md
  docs/interview/system/index.md
  docs/public/img/进程五种状态转换图.png
Labels: 📖 documentation

#92 feat: remove changelog in footer
  docs/.vitepress/plugins/markdownTransform.ts
Labels: 🔨 optimize code

#93 docs: add code study zsxq
  docs/.vitepress/config.ts
  docs/.vitepress/sidebar.ts
  docs/guide.md
  docs/index.md
  docs/public/img/2023coupon.png
  docs/zsxq.md
Labels: 📖 documentation

#94 feat: add changelog & release v0.1.8
  docs/.vitepress/config.ts
  package.json
Labels: 🚀 features, 🎉 chore: release

#95 feat: update week grade
  docs/plan/card.vue
  docs/plan/list1/done.md
Labels: 📖 documentation

#96 feat: update week task & rename config
  .github/workflows/algolia.yml
  crawler.config.json
  docs/plan/card.vue
  docs/plan/list2/done.md
  docs/plan/list2/todo.md
  docs/plan/planet.md
Labels: 📖 documentation

#100 feat: update chodocs logo
  CONTRIBUTORS.svg
  docs/.vitepress/config.ts
  docs/public/chodocs-logo.svg
  docs/public/favicon.ico
Labels: 📖 documentation

#101 feat(theme): support author&contributors frontmatter
  docs/.vitepress/config.ts
  docs/.vitepress/metadata/index.ts
  docs/.vitepress/metadata/types.ts
  docs/.vitepress/plugins/changelog.ts
  docs/.vitepress/plugins/contributors.ts
  docs/.vitepress/plugins/markdownTransform.ts
  docs/.vitepress/theme/components/Changelog.vue
  docs/.vitepress/theme/components/Contributors.vue
  docs/essay/hl1.md
  docs/green/hl-contest/index.md
  docs/guide.md
  docs/interview/browser/cookie.md
  docs/interview/browser/principle/eventLoop.md
  docs/interview/browser/process/index.md
  docs/interview/browser/safety/index.md
  docs/interview/net/http/index.md
  docs/interview/net/tcp/index.md
  docs/interview/react-summary/index.md
  docs/interview/system/index.md
  docs/interview/vue/index.md
  docs/patterns/guide/index.md
  docs/patterns/singleton-pattern/index.md
  docs/plan/list1/done.md
  docs/plan/list1/todo.md
  docs/plan/planet.md
  docs/vite.config.ts
  docs/zsxq.md
  meta/packages.ts
  package.json
  scripts/changelog.ts
  scripts/contributors.ts
  scripts/release.ts
  scripts/updateMetaData.ts
  types/docsTypes.ts
  types/index.ts
  types/metaData.ts
Labels: 🚀 features, 🔨 optimize code

#99 feat: add vitepress local search
  docs/.vitepress/sidebar.ts
  docs/contributors.json
  docs/index.md
  docs/program/vitepress-local-search/index.md
Labels: 📖 documentation, ⚡ pr welcome

#102 feat(docs): content format
  docs/program/vitepress-local-search/index.md
Labels: 📖 documentation

#103 fix(theme): cut index.md of contributors
  docs/.vitepress/plugins/markdownTransform.ts
Labels: 🐛 bug need fix, 🔨 optimize code

#104 feat(docs): update quota & arc gift code
  docs/.vitepress/plugins/markdownTransform.ts
  docs/arc.md
  docs/zsxq.md
Labels: 📖 documentation

#109 fix(tool): left time condition
  docs/tool/off-time/demo.vue
Labels: 🔨 optimize code

#111 feat: del custom algolia
  .github/workflows/algolia.yml
  crawler.config.json
Labels: 🔨 optimize code

#112 feat(algolia): add docs of algolia plus
  docs/.vitepress/sidebar.ts
  docs/program/vitepress-algolia-plus/index.md
  docs/public/program/algolia-comment.jpg
  docs/public/program/algolia-email.png
  docs/zsxq.md
Labels: 📖 documentation

#113 feat(docs): add bilibili algolia video
  docs/program/vitepress-algolia-plus/index.md
Labels: 📖 documentation

#116 docs(program): form submit fail condition desc
  docs/program/vitepress-algolia-plus/index.md
Labels: 📖 documentation

#118 feat(docs): add chodocs original intention & update over
  docs/.vitepress/sidebar.ts
  docs/chodocs.md
  docs/guide.md
  docs/index.md
  docs/zsxq.md
  package.json
Labels: 📖 documentation

#119 feat(docs): add tag link
  docs/zsxq.md
Labels: 📖 documentation

#120 feat(docs): update over
  docs/zsxq.md
Labels: 📖 documentation

#123 feat(plan): update done & score
  docs/plan/card.vue
  docs/plan/list2/done.md
  docs/plan/list2/todo.md
  docs/zsxq.md
Labels: 📖 documentation

#124 feat: update grade
  docs/plan/card.vue
  docs/plan/index.md
  docs/plan/list1/done.md
  docs/public/img/2023plan.png
  docs/public/img/2023plan1.png
Labels: 📖 documentation

#125 feat: change readme
  README.md
Labels: 📖 documentation

#126 feat: each post add copyright
  docs/.vitepress/plugins/markdownTransform.ts
  docs/.vitepress/theme/components/CopyRight.vue
Labels: 🚀 features

#127 chore: release v0.2.0
  package.json
Labels: 🎉 chore: release

#128 fix(code): remove useless code
  docs/.vitepress/theme/components/CopyRight.vue
Labels: 🔨 optimize code

#129 feat(plan): upgrade grade
  docs/plan/card.vue
  docs/plan/list2/done.md
Labels: 📖 documentation

#132 feat: add mock interview
  docs/.vitepress/sidebar.ts
  docs/index.md
  docs/interview/interviewer/index.md
Labels: 📖 documentation

#133 fix: mock interview md style
  docs/interview/interviewer/index.md
Labels: 📖 documentation

#134 docs: update activity
  docs/zsxq.md
Labels: 📖 documentation

#136 feat: add favorites page
  docs/.vitepress/config.ts
  docs/.vitepress/link.ts
  docs/.vitepress/sidebar.ts
  docs/.vitepress/theme/components/NavCard.vue
  docs/favorites.md
  docs/favorites/css.ts
  docs/favorites/material.ts
  docs/favorites/operate.ts
  docs/favorites/regex.ts
  docs/favorites/tool.ts
  docs/favorites/toy.ts
  docs/favorites/tutorial.ts
  docs/favorites/types.ts
Labels: 📖 documentation, 🚀 features

#139 feat(favorites): add interview & acm
  docs/favorites.md
  docs/favorites/interview.ts
Labels: 📖 documentation, 🔨 optimize code

#140 docs: remove info
  docs/index.md
Labels: 📖 documentation

#141 feat(theme): add google analytics plugin
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/plugins/google-analytics.ts
Labels: 🚀 features

#142 feat(theme): auto sidebar plugin(beta)
  docs/.vitepress/sidebar.ts
  docs/.vitepress/theme/plugins/auto-sidebar.ts
Labels: 🔨 optimize code

#143 fix: add overflow hidden style
  docs/.vitepress/theme/components/CopyRight.vue
Labels: 🐛 bug need fix

#144 feat(essay): react documentary
  docs/.vitepress/sidebar.ts
  docs/.vitepress/theme/plugins/autoSidebarBeta.ts
  docs/essay/ch2.md
Labels: 📖 documentation

#146 feat(theme): use arguments object to forward parameters
  .eslintrc.js
  docs/.vitepress/theme/plugins/googleAnalytics.ts
Labels: 🔨 optimize code

#147 chore: add method to solved search
  docs/.vitepress/sidebar.ts
  docs/contributors.json
  docs/index.md
  docs/program/vitepress-algolia-solved/index.md
Labels: 📖 documentation, 👍 good first issue

#148 feat(program): format content
  docs/program/vitepress-algolia-solved/index.md
Labels: 📖 documentation

#149 feat(docs): add contributing page
  README.md
  docs/.vitepress/sidebar.ts
  docs/contributing.md
Labels: 📖 documentation

#150 chore: add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🔨 optimize code

#151 docs: update link
  README.md
Labels: 📖 documentation

#152 feat(theme): add data panel uv pv plugin
  docs/.vitepress/theme/components/DataPanel.vue
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/plugins/busuanzi.ts
  docs/index.md
Labels: 🚀 features

#154 feat(theme): add page info plugin
  docs/.vitepress/plugins/markdownTransform.ts
  docs/.vitepress/theme/components/PageInfo.vue
  docs/.vitepress/theme/types/index.ts
  docs/.vitepress/theme/utils.ts
  docs/arc.md
  docs/guide.md
Labels: 🚀 features, 🔨 optimize code

#155 feat(interview): add js test list
  docs/.vitepress/sidebar.ts
  docs/interview/js/test/1.md
  docs/interview/js/test/2.md
  docs/interview/js/test/3.md
Labels: 📖 documentation

#156 fix(theme): busuanzi page pv
  docs/.vitepress/theme/components/PageInfo.vue
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/plugins/busuanzi.ts
  package.json
  pnpm-lock.yaml
Labels: 🐛 bug need fix, 🔨 optimize code

#157 fix(theme): busuanzi page pv add container
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/PageInfo.vue
Labels: 🐛 bug need fix

#159 style: mobile add px
  docs/.vitepress/theme/components/DataPanel.vue
Labels: 🔨 optimize code

#160 feat(plugin): optimize plugin code
  docs/.vitepress/theme/plugins/autoSidebarBeta.ts
Labels: 🔨 optimize code

#161 chore: release v0.2.1
  docs/contributors.json
  package.json
Labels: 🔨 optimize code, 🎉 chore: release

#162 feat(docs): update video & quota
  docs/favorites.md
  docs/zsxq.md
Labels: 📖 documentation

#164 feat(tool): add github 520
  docs/.vitepress/sidebar.ts
  docs/tool/github520.md
Labels: 📖 documentation

#163 feat(patterns): add observer pattern
  docs/.vitepress/sidebar.ts
  docs/patterns/observer-pattern/index.md
Labels: 📖 documentation

#166 feat(pattern): add module pattern
  docs/.vitepress/sidebar.ts
  docs/patterns/module-pattern/index.md
Labels: 📖 documentation

#167 feat(pattern): add mixin pattern
  docs/.vitepress/sidebar.ts
  docs/patterns/mixin-pattern/index.md
Labels: 📖 documentation

#170 feat(theme): add date time && docs update
  docs/.vitepress/theme/components/PageInfo.vue
  docs/.vitepress/theme/utils/date.ts
  docs/.vitepress/theme/utils/index.ts
  docs/.vitepress/theme/utils/md.ts
  docs/.vitepress/theme/utils/pageInfo.ts
  docs/arc.md
  docs/green/ch1.md
  docs/green/ch2.md
  docs/green/ch3.md
  docs/green/ch4.md
  docs/green/hl-contest/index.md
  docs/patterns/mixin-pattern/index.md
  docs/patterns/module-pattern/index.md
  docs/patterns/observer-pattern/index.md
  docs/zsxq.md
  package.json
  pnpm-lock.yaml
Labels: 📖 documentation, 🚀 features

#171 fix(utils): add dayjs zh-cn
  docs/.vitepress/theme/utils/date.ts
Labels: 🔨 optimize code

#173 feat(docs): iterative version
  docs/public/img/2023coupon.png
  docs/public/img/2023planetPlan.png
  docs/public/img/join.png
  docs/zsxq.md
Labels: 📖 documentation

#174 feat(plan): remove plan category
  docs/.vitepress/config.ts
  docs/.vitepress/sidebar.ts
  docs/.vitepress/theme/components/ContentBox.vue
  docs/plan/card.vue
  docs/plan/index.md
  docs/plan/list1/done.md
  docs/plan/list1/todo.md
  docs/plan/list2/done.md
  docs/plan/list2/todo.md
  docs/plan/planet.md
Labels: 📖 documentation

#175 feat(interview): add interviewer 01 && 02
  docs/.vitepress/sidebar.ts
  docs/interview/interviewer/01.md
  docs/interview/interviewer/02.md
Labels: 📖 documentation

#178 docs: update
  docs/interview/interviewer/02.md
  docs/interview/interviewer/index.md
  docs/zsxq.md
Labels: 📖 documentation

#179 feat(interview): add video src
  docs/.vitepress/sidebar.ts
  docs/arc.md
  docs/interview/interviewer/02.md
  docs/interview/interviewer/03.md
Labels: 📖 documentation
