Repository chodocs/chodocs, pull requests merged in 2023-03, with the labels that each got.

#180 docs: update
  docs/zsxq.md
Labels: 📖 documentation

#182 feat(theme): images to be zoomed in on click
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/styles/main.css
  package.json
  pnpm-lock.yaml
Labels: 🚀 features

#185 feat(patterns): add middleware pattern
  docs/.vitepress/sidebar.ts
  docs/patterns/middleware-pattern/index.md
Labels: 📖 documentation

#186 feat(theme): update site info
  docs/.vitepress/algolia.ts
  docs/.vitepress/config.ts
  docs/.vitepress/meta.ts
  docs/index.md
Labels: 📖 documentation, 🚀 features

#187 style: text update
  docs/.vitepress/config.ts
Labels: 📖 documentation

#188 fix: no clean urls
  docs/.vitepress/config.ts
Labels: 🐛 bug need fix

#189 feat(theme): add alternate site
  README.md
  docs/.vitepress/config.ts
  docs/guide.md
  docs/index.md
Labels: 📖 documentation

#199 feat(theme): custom features links
  docs/index.md
Labels: 🚀 features

#201 feat(theme): use @vite-pwa/vitepress and update docs home
  docs/.vitepress/config.ts
  docs/.vitepress/meta.ts
  docs/.vitepress/plugins/pwa.ts
  docs/.vitepress/theme/components/HomeContributors.vue
  docs/contributors.json
  docs/contributors.ts
  docs/index.md
  package.json
  pnpm-lock.yaml
  scripts/update.ts
  scripts/utils.ts
Labels: 📖 documentation, 🚀 features

#203 feat(docs): adjust-the-document-directory-structure
  README.md
  docs/.vitepress/config.ts
  docs/.vitepress/sidebar.ts
  docs/public/images/icons/android-chrome-192x192.png
  docs/public/images/icons/android-chrome-512x512.png
  docs/public/images/icons/apple-touch-icon.png
Labels: 📖 documentation

#206 feat(pattern): add hoc pattern
  docs/.vitepress/sidebar.ts
  docs/patterns/hoc-pattern/index.md
Labels: 📖 documentation

#211 feat(docs): add weekly learning
  docs/.vitepress/sidebar.ts
  docs/weekly/20230301.md
  docs/weekly/guide.md
Labels: 📖 documentation

#210 feat:add Isolcat's Interview Experience
  docs/.vitepress/sidebar.ts
  docs/interview/isolcat/index.md
Labels: 📖 documentation

#212 fix: eslint resolve md error
  docs/.vitepress/sidebar.ts
  docs/contributing.md
  docs/interview/isolcat/index.md
  docs/weekly/20230301.md
Labels: 📖 documentation

#213 feat(docs): update readme and guide
  README.md
  docs/.vitepress/config.ts
  docs/guide.md
Labels: 📖 documentation

#214 chore: release v0.2.2
  docs/contributors.json
  package.json
Labels: 📖 documentation, 🎉 chore: release
